#!/usr/bin/env bash

#####################
# Developed by {{author|Luiz Felipe}}.
#   {{github|https://github.com/Silva97}}
#   {{email|felipe.silva337@yahoo.com}}
#
# Distributed under the {{license|MIT License}}.
# For see more details, see the LICENSE file.
#####################
